# Generated by Django 2.0.1 on 2018-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_quantity', models.CharField(max_length=511)),
                ('user', models.IntegerField()),
            ],
        ),
    ]
