# Generated by Django 2.0.1 on 2018-07-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(blank=True, max_length=100)),
                ('address_number', models.IntegerField(blank=True, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_postcode', models.CharField(blank=True, max_length=10)),
                ('address_nation', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
